language: ruby
args: --without development debug
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database allincome_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rake
notifications:
  recipients:
    - jason@wieringa.co
